export const golfCourses = [
    { name: "Cape Wickham", rank: 1 },
    { name: "Royal Melbourne (West)", rank: 2 },
    { name: "Kingston Heath", rank: 3 },
    { name: "Barnbougle Dunes", rank: 4 },
    { name: "Peninsula Kingswood (North)", rank: 5 },
    { name: "New South Wales", rank: 6 },
    { name: "Barnbougle Lost Farm", rank: 7 },
    { name: "Royal Melbourne (East)", rank: 8 },
    { name: "Royal Adelaide", rank: 9 },
    { name: "Victoria", rank: 10 },
    { name: "Metropolitan", rank: 11 },
    { name: "The National (Moonah)", rank: 12 },
    { name: "Ocean Dunes", rank: 13 },
    { name: "Cathedral", rank: 14 },
    { name: "Peninsula Kingswood (South)", rank: 15 },
    { name: "The National (Gunnamatta)", rank: 16 },
    { name: "Lake Karrinyup", rank: 17 },
    { name: "Kooyonga", rank: 18 },
    { name: "The National (Old)", rank: 19 },
    { name: "The Australian", rank: 20 },
    { name: "Joondalup (Quarry/Dune)", rank: 21 },
    { name: "The Lakes", rank: 22 },
    { name: "Barwon Heads", rank: 23 },
    { name: "Woodlands", rank: 24 },
    { name: "St Andrews Beach", rank: 25 },
    { name: "The Dunes", rank: 26 },
    { name: "Yarra Yarra", rank: 27 },
    { name: "Royal Queensland", rank: 28 },
    { name: "Royal Canberra (Westbourne)", rank: 29 },
    { name: "Hamilton Island", rank: 30 },
    { name: "Newcastle", rank: 31 },
    { name: "Glenelg", rank: 32 },
    { name: "13th Beach (Beach)", rank: 33 },
    { name: "Bonville", rank: 34 },
    { name: "Magenta Shores", rank: 35 },
    { name: "Lonsdale Links", rank: 36 },
    { name: "The Grand", rank: 37 },
    { name: "The Cut", rank: 38 },
    { name: "Bonnie Doon", rank: 39 },
    { name: "Sanctuary Cove (Pines)", rank: 40 },
    { name: "Brookwater", rank: 41 },
    { name: "Grange (West)", rank: 42 },
    { name: "Elanora", rank: 43 },
    { name: "Terrey Hills", rank: 44 },
    { name: "Moonah Links (Legends)", rank: 45 },
    { name: "St Michael's", rank: 46 },
    { name: "Concord", rank: 47 },
    { name: "Moonah Links (Open)", rank: 48 },
    { name: "Portsea", rank: 49 },
    { name: "Port Fairy", rank: 50 },
    { name: "Links Hope Island", rank: 51 },
    { name: "Grange (East)", rank: 52 },
    { name: "The Vintage", rank: 53 },
    { name: "Spring Valley", rank: 54 },
    { name: "The Western Australian", rank: 55 },
    { name: "Sorrento", rank: 56 },
    { name: "Kalgoorlie", rank: 57 },
    { name: "Avondale", rank: 58 },
    { name: "Sandy Links", rank: 59 },
    { name: "Bougle Run", rank: 60 },
    { name: "Links Lady Bay", rank: 61 },
    { name: "Curlewis", rank: 62 },
    { name: "Cottesloe", rank: 63 },
    { name: "13th Beach (Creek)", rank: 64 },
    { name: "Pelican Waters", rank: 65 },
    { name: "Pacific Dunes", rank: 66 },
    { name: "Rosebud (North)", rank: 67 },
    { name: "Meadow Springs", rank: 68 },
    { name: "Lakelands", rank: 69 },
    { name: "Glades", rank: 70 },
    { name: "Mount Compass", rank: 71 },
    { name: "RACV Cape Schanck", rank: 72 },
    { name: "Killara", rank: 73 },
    { name: "Sanctuary Lakes", rank: 74 },
    { name: "Black Bull", rank: 75 },
    { name: "Sanctuary Cove (Palms)", rank: 76 },
    { name: "The Heritage (Henley)", rank: 77 },
    { name: "Brisbane", rank: 78 },
    { name: "Settlers Run", rank: 79 },
    { name: "Palmer Coolum", rank: 80 },
    { name: "Stonecutters Ridge", rank: 81 },
    { name: "Mollymook (Hilltop)", rank: 82 },
    { name: "Pacific Harbour", rank: 83 },
    { name: "Narooma", rank: 84 },
    { name: "The Heritage (St John)", rank: 85 },
    { name: "Castle Hill", rank: 86 },
    { name: "Twin Waters", rank: 87 },
    { name: "Cypress Lakes", rank: 88 },
    { name: "Federal", rank: 89 },
    { name: "Monash", rank: 90 },
    { name: "Secret Harbour", rank: 91 },
    { name: "Riversdale", rank: 92 },
    { name: "Warrnambool", rank: 93 },
    { name: "RACV Royal Pines (Green/Gold)", rank: 94 },
    { name: "Royal Fremantle", rank: 95 },
    { name: "Maroochy River", rank: 96 },
    { name: "Forster Tuncurry (Tuncurry)", rank: 97 },
    { name: "Murray Downs", rank: 98 },
    { name: "Albany", rank: 99 },
    { name: "Noosa Springs", rank: 100 }
];
